### ISSUE TITLE
students don't like the format of these exercises

### ISSUE THREAD

**Issue by mikkelrd** [DevMountain/callbackPractice#18]
two common themes in feedback on this repo are:
A) it feels like a an annoying guessing game where they often aren't even sure what is being asked because there is no prompt in the first place
B) it seems like a backwards way to practice callbacks, with every question asking for simply an invocation of a callback that is already defined. perhaps there should be more variance in the structure of expected answers. some asking you to invoke a callback that has already been defined, some asking to define the callback function, some asking for all of it?

**Comment by asBrettisay** [comment]
@mikkelrd Thanks for providing this feedback. Let's look a little deeper than themes for a concrete example. Did a student tell you they were specifically having issues with one specific problem?

**Comment by r-walsh** [comment]
@asBrettisay  So I was reviewing this project with plans of updating for ES6, 100% agree with Mikkel that this feels like a very backwards way of teaching callbacks. I feel there should be more sections where students write the callback instead of just using a callback that is passed in. Could be a good opportunity to teach some of the more common array methods.

**Comment by devlemire** [comment]
I will spin up a version 2 of this assignment that may be a better format. It will uses the existing problems.

**Comment by devlemire** [comment]
My purposed solution is on the v2 and v2-solution branches.
